### ISSUE TITLE
Request has been deprecated. 

### ISSUE THREAD

**Issue by NotMoni** [prescottprue/firebase-tools-extra#31]
Hey,

It looks like you use the request package in your code.
Request has been deprecated. 
Request package is unmaintained and will no longer be updated by the publisher.
You should switch to another HTTP request library for Node.js

Some other Library:
[Node-fetch](https://www.npmjs.com/package/node-fetch)
[Got](https://www.npmjs.com/package/got)
[Axios](https://www.npmjs.com/package/axios)

**Comment by prescottprue** [comment]
That is not the case for any code contained within this project and it is a not a direct dependency or dev dependency. Maybe you are finding it from one of the dependencies?

**Comment by prescottprue** [comment]
After looking through the yarn.lock, it appears it is a dependency of the following libraries:

```
@firebase/testing
firebase-tools
firebase-tools > google-auto-auth
firebase-tools > universal-analytics
```

Both of these are dev dependencies. Is this where you were seeing request? Is this creating an issue for you in some way?

`firebase-tools` is used to run the firebase emulators for tests, and `@firebase/testing` is used in [the unit tests themselves](https://github.com/prescottprue/firebase-tools-extra/blob/master/test/unit/index.spec.ts#L2).

**Comment by NotMoni** [comment]
Yea, I was just letting you know.

**Comment by prescottprue** [comment]
Going to close since it will be up to those libraries to update
